name: Deploy Wagner REPL to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Wagnostic Dependencies
        run: |
          mkdir -p ../runners/web
          wget https://raw.githubusercontent.com/jardimdanificado/wagnostic/master/runners/web/sysroot.json -O ../runners/web/sysroot.json
          wget https://raw.githubusercontent.com/jardimdanificado/wagnostic/master/runners/web/cc.wasm -O ../runners/web/cc.wasm
          wget https://raw.githubusercontent.com/jardimdanificado/wagnostic/master/runners/web/runner.js -O ../runners/web/runner.js

      - name: Build Web REPL
        run: |
          cd repl
          python3 build_repl.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './repl'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
